name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  #schedule:
    # Update automatically on weekdays during work hours
    #- cron: '0 10,13,16 * * 1-5'
    # ... and every night
    #- cron: '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        cache: pip
    - name: Install dependencies
      run: python -m pip install -r requirements.txt
    - name: Build
      run: make -j3
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: yarn
        cache-dependency-path: analysaattori/yarn.lock
    - run: yarn
      working-directory: analysaattori
    - run: yarn build -- --base=/palkkakysely/analysaattori/
      working-directory: analysaattori
      env:
        GENERATE_SOURCEMAP: 'false'
    - run: cp -a analysaattori/dist ./out/analysaattori
    - run: ls -laR out
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.0.0
      with:
        branch: gh-pages
        folder: out
        clean: false
      if: ${{ github.event_name == 'push' }}
